config/routes.rb
Rails.application.routes.draw do

  root 'signin#index'

  get '/courses/:id/image', to: 'courses#show_image'
  get '/snippets/:id/image', to: 'snippets#show_image'
  get '/users/:id/image', to: 'users#show_image'
  get '/outcome_files/:id/upload', to: 'outcome_files#show_upload'
  resources :courses, only: %i[create new edit update destroy]
  resources :enrollments, only: %i[create new edit update destroy]
  resources :terms, only: %i[create new update destroy]
  match ':controller(/:action(/:id(.:format)))', via: %i[get post put patch]

  mount PdfjsViewer::Rails::Engine => '/pdfjs', as: 'pdfjs'

end

app/models/enrollment.rb
# == Schema Information
#
# Table name: enrollments
#
#  id          :integer          not null, primary key
#  course_id   :integer
#  user_id     :integer
#  role        :string
#  group_index :integer          default(0)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  sourced_id  :string
#

class Enrollment < ApplicationRecord
  belongs_to :course
  belongs_to :user
  validates :course_id, presence: true
  validates :course_id, uniqueness: { scope: :user_id }
  # FIXME: Group work
  validates :group_index, inclusion: { in: (0...COURSE_GROUP_MAX_SIZE).to_a }
  validates :role, inclusion: { in: %w[manager assistant learner] }
  validates :user_id, presence: true

  # ====================================================================
  # Public Functions
  # ====================================================================
  def self.sync_roster(course_id, user_ids, renrollments)
    # Create and Update with OneRoster data
    ids = []
    renrollments.each do |re|
      enrollment = find_or_initialize_by(sourced_id: re['sourcedId'])
      user_id = user_ids.find{|u| u[:sourced_id] == re['userSourcedId']}[:id]
      role = to_lepo_role re['role']
      if enrollment.update_attributes(course_id: course_id, user_id: user_id, role: role)
        ids.push enrollment.id
      end
    end
    ids
  end

  def self.destroy_unused(course_id, enrollment_ids)
    enrollments = where(course_id: course_id).where.not(id: enrollment_ids)
    ids = []
    unless enrollments.empty?
      ids = enrollments.destroy_all
      ids.map{|e| e.user_id}
    end
    ids
  end

  def self.update_managers(course_id, current_ids, ids)
    transaction do
      # unregister
      current_ids.each do |c_id|
        if ids.include? c_id
          # neednot add or delete
          ids.delete c_id
        else
          enrollment = Enrollment.find_by(course_id: course_id, user_id: c_id, role: 'manager')
          enrollment.destroy! if enrollment.destroyable?
        end
      end
      # register
      ids.each do |id|
        enrollment = Enrollment.new(course_id: course_id, user_id: id, role: 'manager')
        enrollment.save!
      end
    end
    return true
  rescue StandardError
    logger.info(e.inspect)
    return false
  end

  def to_roster_hash
    raise if user.sourced_id.nil?
    hash = {
      classSourcedId: course.sourced_id,
      schoolSourcedId: Rails.application.credentials.oneroster[:school_sourced_id],
      userSourcedId: user.sourced_id,
      role: Enrollment.to_roster_role(role)
    }
  end

  def self.to_lepo_role role
    case role
    when 'teacher'
      'manager'
    when 'aide'
      'assistant'
    when 'student'
      'learner'
    else
      raise
    end
  end

  def self.to_roster_role role
    case role
    when 'manager'
      'teacher'
    when 'assistant'
      'aide'
    when 'learner'
      'student'
    else
      raise
    end
  end

  def self.creatable?(course_id, operator_id, role = nil)
    # Not permitted when SYSTEM_ROSTER_SYNC is :suspended
    return false if %i[on off].exclude? SYSTEM_ROSTER_SYNC
    course = Course.find course_id
    return false if course.status == 'archived'
    raise 'ERROR: Assistant can not create manager' if (course.assistant?(operator_id) && role == 'manager')
    user = User.find operator_id
    user.system_staff? || course.staff?(operator_id)
  end

  def destroyable?(operator_id)
    return false if new_record?
    if role == 'manager'
      course = Course.find_enabled_by course_id
      return false if course.evaluator? user_id
      manager_num = Enrollment.where(course_id: course_id, role: 'manager').size
      return false if manager_num == 1
    end
    updatable? operator_id
  end

  def updatable?(operator_id, role = nil)
    # FIXME updat_to role must be inputted
    return false if SYSTEM_ROSTER_SYNC == :on && sourced_id.blank?
    return false if SYSTEM_ROSTER_SYNC == :off && sourced_id.present?
    Enrollment.creatable?(course.id, operator_id, role)
  end
end

app/controllers/enrollments_controller.rb
require 'csv'
class EnrollmentsController < ApplicationController
  include RosterApi
  include ::UsersController::AllActions
  include ::StickiesController::AllActions
  # ====================================================================
  # Public Functions
  # ====================================================================
  def new
    get_resources
    @form_category = ''
    @member_role = 'learner'
    render 'layouts/renders/main_pane', locals: { resource: 'enrollments/new' }
  end

  def create
    enrollment = Enrollment.find_or_initialize_by(course_id: params[:enrollment][:course_id], user_id: params[:enrollment][:user_id])
    role = params[:enrollment][:role]
    begin
      raise unless enrollment.new_record?
      raise unless Enrollment.creatable? enrollment.course_id, session[:id], role
      Enrollment.transaction do
        enrollment.role = role
        enrollment.save!
        if SYSTEM_ROSTER_SYNC == :on
          payload = {enrollment: enrollment.to_roster_hash}
          response = request_roster_api('/enrollments/', :post, payload)
          enrollment.update_attributes!(sourced_id: response['enrollment']['sourcedId'])
        end
      end
    rescue => error
      notify_error error, t('controllers.enrollments.creation_failed')
    end

    case params[:form_category]
    when 'search'
      ajax_search_candidates
    when 'csv'
      ajax_csv_candidates
    else
      new
    end
  end

  def edit
    @enrollment = Enrollment.find params[:id]
    @course = Course.find_enabled_by @enrollment.course_id
    @user = @enrollment.user
    render 'layouts/renders/main_pane', locals: { resource: 'enrollments/edit' }
  end

  def update
    @enrollment = Enrollment.find params[:id]
    @course = Course.find_enabled_by @enrollment.course_id
    @user = @enrollment.user
    from_role = @enrollment.role
    to_role = params[:enrollment][:role]
    begin
      raise unless @enrollment.updatable? session[:id]
      raise t('controllers.enrollments.evaluator_must_be_manager') if (to_role != 'manager') && (@course.evaluator? @user.id)
      Enrollment.transaction do
        @enrollment.update_attributes!(enrollment_params)
        if (SYSTEM_ROSTER_SYNC == :on) && (to_role != from_role)
          payload = {enrollment: @enrollment.to_roster_hash}
          response = request_roster_api("/enrollments/#{@enrollment.sourced_id}", :put, payload)
        end
      end
      render_index
    rescue => error
      notify_error error, t('controllers.enrollments.update_failed')
      render 'layouts/renders/main_pane', locals: { resource: 'enrollments/edit' }
    end
  end

  def destroy
    @enrollment = Enrollment.find params[:id]
    @course = Course.find_enabled_by @enrollment.course_id
    @user = @enrollment.user
    begin
      raise t('controllers.enrollments.evaluator_must_be_manager') if (@course.evaluator? @user.id)
      raise unless @enrollment.destroyable? session[:id]
      Enrollment.transaction do
        @enrollment.destroy!
        response = request_roster_api("/enrollments/#{@enrollment.sourced_id}", :delete) if (SYSTEM_ROSTER_SYNC == :on)
      end
      render_index
    rescue => error
      notify_error error, t('controllers.enrollments.delete_failed')
      render 'layouts/renders/main_pane', locals: { resource: 'enrollments/edit' }
    end
  end

  def ajax_index
    set_nav_session params[:nav_section], 'enrollments', params[:nav_id].to_i
    get_resources
    render 'layouts/renders/all', locals: { resource: 'index' }
  end

  def ajax_show(transition = false)
    @selected_user = User.find params[:id]
    get_resources
    @stickies = course_stickies_by_user @selected_user.id, session[:nav_id]
    if transition
      render 'layouts/renders/all', locals: { resource: 'users/user' }
    else
      render 'layouts/renders/main_pane', locals: { resource: 'users/user' }
    end
  end

  def ajax_show_with_transition
    # ajax show with in-course transition
    set_nav_session session[:nav_section], 'enrollments', session[:nav_id]
    ajax_show true
  end

  def ajax_edit_group
    get_resources
    render 'layouts/renders/main_pane', locals: { resource: 'enrollments/edit_group' }
  end

  def ajax_csv_candidates
    @form_category = 'csv'
    @member_role = ''
    @search_word = ''
    @candidates_csv = params[:candidates_csv] ? params[:candidates_csv] : ''

    get_resources
    manageable = @course.manager_changeable? session[:id]
    @candidates = csv_to_member_candidates @candidates_csv, manageable, 'course', @course.id
    render 'layouts/renders/resource', locals: { resource: 'enrollments/new' }
  end

  def ajax_search_candidates
    @form_category = 'search'
    @member_role = params[:member_role] ? params[:member_role] : ''
    @search_word = params[:search_word] ? params[:search_word] : ''
    @candidates_csv = ''

    candidates = User.search @search_word
    get_resources
    case @member_role
    when 'manager'
      candidates = delete_existing candidates, @course.managers
    when 'assistant'
      candidates = delete_existing candidates, @course.assistants
      candidates = delete_existing candidates, @course.managers unless @course.manager_changeable? session[:id]
    when 'learner'
      candidates = delete_existing candidates, @course.learners
      candidates = delete_existing candidates, @course.managers unless @course.manager_changeable? session[:id]
    end

    if session[:nav_id]
      current_categories = []
      candidates.each do |cn|
        current_relation = Enrollment.find_by(user_id: cn.id, course_id: session[:nav_id])
        current_role = current_relation ? current_relation.role : ''
        current_categories.push current_role
      end
      @candidates = candidates.zip current_categories, Array.new(candidates.size, @member_role)
    end
    render 'layouts/renders/resource', locals: { resource: 'enrollments/new' }
  end

  def ajax_update_group
    course_id = session[:nav_id]
    user_id = params[:user_id]
    group_index = params[:group_index]

    enrollment = Enrollment.find_by(user_id: user_id, course_id: course_id)
    enrollment.update_attributes(group_index: group_index)
    get_resources
    render 'layouts/renders/main_pane', locals: { resource: 'enrollments/edit_group' }
  end

  def ajax_get_managers
    manager_ids = params[:manager_ids].nil? ? [] : params[:manager_ids]
    case params[:category]
    when 'release' then
      course_user = Enrollment.find_by(course_id: params[:course_id], user_id: params[:manager_id])
      if course_user.nil? || course_user.deletable?
        manager_ids.delete(params[:manager_id])
      else
        flash.now[:message] = 'レッスンの評価担当者、またはコース内でふせんを記載している場合は削除できません。'
        flash[:message_category] = 'error'
      end
    when 'add' then
      user = User.find_by(id: params[:manager_id])
      manager_ids.push(user.id) unless user.nil?
    end
    managers = []
    manager_ids.each do |manager_id|
      user = User.find_by(id: manager_id)
      managers.push(user) unless user.nil?
    end
    render 'courses/renders/tmp_managers', locals: { managers: managers, course_id: session[:nav_id], message: flash.now[:message], message_category: flash[:message_category] }
  end

  def autocomplete_manager
    if invalid_autocomplete_request?(params[:search_word])
      render json: []
    else
      users = User.autocomplete params[:search_word]
      user_suggestions = []
      excludes = exclude_members(params[:tmp_managers], params[:course_id])
      users.each do |u|
        # for the case given_name is nil, to_s is added
        label = u.signin_name + ', ' + u.family_name + ' ' + u.given_name.to_s
        user_suggestions.push(value: u.id, label: label) unless excludes.include?(u.id)
      end
      user_suggestions.slice!(AUTOCOMPLETE_MAX_SIZE...user_suggestions.size)
      render json: user_suggestions
    end
  end

  # ====================================================================
  # Private Functions
  # ====================================================================

  private

  def enrollment_params
    params.require(:enrollment).permit(:role)
  end

  def get_resources
    @course = Course.find_enabled_by session[:nav_id]
    @managers = User.sort_by_signin_name @course.managers
    @assistants = User.sort_by_signin_name @course.assistants
    @learners = User.sort_by_signin_name @course.learners
  end

  def render_index
    @managers = User.sort_by_signin_name @course.managers
    @assistants = User.sort_by_signin_name @course.assistants
    @learners = User.sort_by_signin_name @course.learners
    render 'layouts/renders/main_pane', locals: { resource: 'index' }
  end

  def invalid_autocomplete_request?(param)
    request.get? || param.nil? || param.empty? || !User.system_staff?(session[:id])
  end

  def exclude_members(tmp_managers, course_id)
    excludes = tmp_managers.nil? ? [] : tmp_managers.map(&:to_i)
    # Considering that the value of course_id is -1 (new course), use find_by instead of find
    course = Course.find_enabled_by course_id
    return excludes if course.nil?
    learners = course.learners
    learners.each do |l|
      excludes.push(l.id)
    end
    assistants = course.assistants
    assistants.each do |a|
      excludes.push(a.id)
    end
    excludes
  end
end

app/views/enrollments/_edit.html.erb
<div id="enrollment-resource" class="scroll-pane">
  <div class="row">
    <div class="col-md-12">
      <h1>コースメンバーの編集</h1>
      <%= render partial: 'role_info' %>
      <%= form_for @enrollment, html: {id: 'enrollment_form', remote: true} do |f| %>
      <%= render partial: 'layouts/system_message', locals: {message: flash[:message], message_category: flash[:message_category]} %>
      <div class="bordered-block">
        <div class="form-group row align-items-center">
          <div class="col-md-3 col-form-label text-sm-right">
            <%= t('activerecord.attributes.enrollment.course') %>
          </div>
          <div class="col-md-8">
            <%= @course.title %>
          </div>
        </div>
        <div class="form-group row align-items-center">
          <div class="col-md-3 col-form-label text-sm-right">
            <%= t('activerecord.attributes.enrollment.user') %>
          </div>
          <div class="col-md-8">
            <%= @user.full_name %>
          </div>
        </div>
        <div class="form-group row align-items-center">
          <%= f.label :role, t('activerecord.attributes.enrollment.role'), class: 'col-md-3 col-form-label text-sm-right' %>
          <div class="col-md-8">
            <%= f.select :role, member_role_options('enrollment'), {}, {class: 'form-control'} %>
          </div>
        </div>
        <%= render partial: 'layouts/buttons/cancel', locals: {action_hash: {action: 'ajax_index', nav_section: session[:nav_section], nav_id: @course.id}} %>
        <%= render(partial: 'layouts/buttons/update') if @enrollment.updatable? session[:id] %>
        <% if @enrollment.destroyable? session[:id] %>
        <span style="margin-left:3rem;">
          <%= render partial: 'layouts/buttons/rest_delete', locals: {path: enrollment_path(@enrollment.id), id_attr: ''} %>
        </span>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/enrollments/_edit_group.html.erb
<div id="enrollment-resource" class="scroll-pane">
  <div class="row">
    <div class="col-md-12">
			<div class="block">
				<!-- With Groups -->
				<!-- #FIXME: Group work -->
				<table class="table edit-group">
					<tr>
						<th><%= t('activerecord.attributes.user.signin_name') %></th>
						<th><%= t('activerecord.others.user.full_name') %></th>
						<th><%= t('activerecord.attributes.enrollment.group') %></th>
					</tr>
					<% @course.learners.each do |l| %>
					<tr>
						<td><%= l.signin_name %></td>
						<td><%= l.full_name %></td>
						<td>
							<div class="btn-group" data-toggle="buttons-radio">
								<ul class="nav nav-pills">
									<% @course.groups_count.times do |g| %>
									<% if g == @course.group_index_for(l.id) %>
									<li class="active"><span class="badge badge-primary" style="font-size: 1rem;"><%= t('.group', index: g + 1) %></span></li>
									<% else %>
									<li><%= link_to(t('.group', index: g + 1), {action: 'ajax_update_group', user_id: l.id, group_index: g}, {remote: true}) %></li>
									<% end %>
									<% end %>
								</ul>
							</div>
						</td>
					</tr>
					<% end %>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/enrollments/_index.html.erb
<div id="enrollment-resource" class="scroll-pane">
	<div class="row">
		<div class="col-md-12">
			<!-- <div class="block"> -->
			<!-- FIXME: No need? -->
			<!-- <%#= render(partial: 'signin_reports') %> -->
			<!-- </div> -->
			<div class="block">
				<%= render(partial: 'members', locals: {title: t('activerecord.attributes.course.managers'), users: @course.managers}) %>
				<%= render(partial: 'members', locals: {title: t('activerecord.attributes.course.assistants'), users: @course.assistants}) %>

				<% if @course.groups_count == 1 %>
				<!-- Without Groups (Only One Group) -->
				<%= render(partial: 'members', locals: {title: t('activerecord.attributes.course.learners'), users: @course.learners}) %>

				<% else %>
				<!-- With Groups -->
				<!-- #FIXME: Group work -->
				<% @course.groups_count.times do |g| %>
				<% learners = @course.learners_in_group g %>
				<%= render(partial: 'members', locals: {title: t('.group', index: g + 1), users: learners}) %>
				<% end %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/enrollments/_members.html.erb
<% if users.size > 0 %>
<div class="card">
  <h2 class="card-header"><%= title %> : <%= t('.users', num: users.size) %></h2>
  <div class="card-body" style="padding: 1px;">
    <table class="table table-sm table-striped user-table">
      <% users.each do |user| %>
      <tr>
        <td class="image-td">
          <%= render partial: 'layouts/image', locals: {obj: user, fa_class: 'fa-user', img_px: '40'} %>
        </td>
        <td class="name-td">
          <%= link_to user.full_name_all, {controller: 'enrollments', action: 'ajax_show', id: user.id}, remote: true %>
        </td>
        <td class="button-td">
          <% if current_user.system_staff? || @course.staff?(current_user.id) %>
          <% enrollment = Enrollment.find_by(user_id: user.id, course_id: @course.id) %>
          <%= render partial: 'layouts/buttons/rest_edit', locals: {path: edit_enrollment_path(enrollment), class_attr: 'btn btn-primary'} %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>
<% end %>

app/views/enrollments/_new.html.erb
<div id="enrollment-resource" class="scroll-pane">
  <div class="row">
    <div class="col-md-12">
      <%= render partial: 'role_info' %>
      <%= render partial: 'layouts/system_message', locals: {message: flash[:message], message_category: flash[:message_category]} %>
      <%= render(partial: 'layouts/search_members', locals: {update_model: 'enrollment', resource_id: @course.id}) %>
      <%= render(partial: 'layouts/csv_members', locals: {update_model: 'enrollment', resource_id: @course.id}) %>
      <% current_enrollments = @course.managers.zip Array.new(@course.managers.size, 'manager'), Array.new(@course.managers.size, '') %>
      <% current_enrollments = current_enrollments.concat(@course.assistants.zip Array.new(@course.assistants.size, 'assistant'), Array.new(@course.assistants.size, '')) %>
      <% current_enrollments = current_enrollments.concat(@course.learners.zip Array.new(@course.learners.size, 'learner'), Array.new(@course.learners.size, '')) %>
      <%= render(partial: 'layouts/member_candidates', locals: {title: '現在のメンバー', category: 'course', form_category: 'index', users: current_enrollments, resource_id: @course.id, footer:''}) %>
      <p>
        <%= render partial: 'layouts/buttons/ok', locals: {action_hash: {action: 'ajax_index', nav_section: session[:nav_section], nav_id: @course.id}} %>
      </p>
    </div>
  </div>
</div>

app/views/enrollments/_role_info.html.erb
<div class="block alert alert-info">
  <table class="table table-sm role-info">
    <thead>
      <tr>
        <th></th>
        <th style="text-align:center;"><%= t('activerecord.attributes.course.managers') %></th>
        <th style="text-align:center;"><%= t('activerecord.attributes.course.assistants') %></th>
        <th style="text-align:center;"><%= t('activerecord.attributes.course.learners') %></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th><%= t('.view_content') %></th>
        <td><i class="fa fa-check"></i></td>
        <td><i class="fa fa-check"></i></td>
        <td><i class="fa fa-check"></i></td>
      </tr>
      <tr>
        <th><%= t('.submit_assignment') %></th>
        <td></td>
        <td></td>
        <td><i class="fa fa-check"></i></td>
      </tr>
      <tr>
        <th><%= t('.evaluate_assignment') %></th>
        <td><i class="fa fa-check"></i></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <th><%= t('.edit_course') %></th>
        <td><i class="fa fa-check"></i></td>
        <td><i class="fa fa-check"></i></td>
        <td></td>
      </tr>
      <tr>
        <th><%= t('.edit_course_member') %></th>
        <td><i class="fa fa-check"></i></td>
        <td><i class="fa fa-check"></i></td>
        <td></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/enrollments/_signin_report.html.erb
<tr>
	<td class="width160"><%= signin_report["full_name"] %></td>
	<% if signin_report["last_signin_at"].kind_of?(Time) %>
	<td class="width160 text-center"><%= l(signin_report["last_signin_at"], format: :default) %></td>
	<% else %>
	<td class="width160 text-center">---</td>
	<% end %>
	<td class="text-center"><%= signin_report["access_num_week1"] %></td>
	<td class="text-center"><%= signin_report["access_num_week2"] %></td>
</tr>

app/views/enrollments/_signin_reports.html.erb
<div class="report-card card">
  <h2>システムアクセス</h2>
  <!-- <%# if manager_report?(@course_role, @learners) %>
  <div class="card-right-top">
    <a data-toggle="collapse" href="#signin-report-details" aria-expanded="false" aria-controls="signin-report-details">
      <i class="fa fa-chevron-circle-down"></i> <%#= t('.show_learners_details') %>
    </a>
  </div>
  <%# end %> -->

  <table id="signins" class="table table-condensed">
    <thead>
      <tr>
        <th class="width160" rowspan="2"></th>
        <th class="width160 text-center" rowspan="2">最終アクセス</th>
        <th class="text-center" colspan="2">アクセス数</th>
      </tr>
      <tr>
        <th class="width160 text-center">1〜7日前</th>
        <th class="width160 text-center">8〜14日前</th>
      </tr>
    </thead>

    <tbody>
      <%= render partial: 'signin_report', collection: signin_reports(@learners) %>
    </tbody>

    <!-- <%# if manager_report?("manager", @learners) %>
    <%# if manager_report?(@course_role, @learners) %>
    <tbody id="signin-report-details" class="collapse">
    <%#= render partial: 'signin_report', collection: toggle_signin_reports(@learners) %>
    </tbody>
    <%# end %> -->

  </table>
</div>

app/views/enrollments/_toolbar.html.erb
<% case controller.action_name when 'ajax_index', 'update', 'destroy' -%>
<nav id="sub-nav">
  <%= render partial: 'layouts/breadcrumb', locals: {crumbs: [['']]} %>
</nav>
<% if Enrollment.creatable? @course.id, session[:id] %>
<div id="toolbar-btns">
  <div class="btn-group">
    <%= link_to(new_enrollment_path, {class: 'toolbar-btn', remote: true}) do %>
    <i class='fa fa-plus'></i> <%= t('activerecord.models.enrollment') %>
    <% end %>

    <% if @course.groups_count > 1 %>
    <a style="cursor:pointer;" class="toolbar-btn dropdown-toggle" data-toggle="dropdown"><i class="fa fa-cog fa-2x"></i></a>
    <div class="dropdown-menu">
      <%= link_to({action: 'ajax_edit_group'}, {class: 'dropdown-item', remote: true}) do %>
      <i class="fa fa-pencil"></i> <%= t('.edit_group') %>
      <% end %>
    </div>
    <% end %>
  </div>
</div>
<% end %>

<% when 'edit' %>
<nav id="sub-nav">
  <%= render partial: 'layouts/breadcrumb', locals: {crumbs: [['', {action: 'ajax_index', nav_section: session[:nav_section], nav_id: @course.id}], [@user.full_name]]} %>
</nav>
<div id="toolbar-btns">
  <%= render partial: 'layouts/buttons/cancel', locals: {action_hash: {action: 'ajax_index', nav_section: session[:nav_section], nav_id: @course.id}, id_attr: 'toolbar-cancel-btn', class_attr: 'toolbar-btn'} %>
  <%= render(partial: 'layouts/buttons/toolbar_update', locals: {onclick_txt: "$('#enrollment_form').submit()"}) if @enrollment.updatable? session[:id] %>
</div>

<% when 'new', 'create', 'ajax_edit_group', 'ajax_update_group' %>
<div id="toolbar-btns">
  <%= render partial: 'layouts/buttons/ok', locals: {action_hash: {action: 'ajax_index', nav_section: session[:nav_section], nav_id: @course.id}, id_attr: 'toolbar-ok-btn', class_attr: 'toolbar-btn'} %>
</div>

<% when 'ajax_show' -%>
<nav id="sub-nav">
  <%= render partial: 'layouts/breadcrumb', locals: {crumbs: [['', {action: 'ajax_index', nav_section: session[:nav_section], nav_id: @course.id}], [@selected_user.full_name]]} %>
</nav>
<% end -%>